wvtool: Do not fail due to UnicodeDecodeError
Sometimes the output produced by run program is not valid UTF-8 and Python
fails with errors like this:

    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 0: invalid start byte

This change should fix this - these errors are now repalced with the '�'
character.